# Generated by Django 5.1.1 on 2024-09-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="user",
            new_name="user_id",
        ),
    ]
