# Generated by Django 5.1.1 on 2024-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockApp", "0002_rename_user_transaction_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Initial_balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
